///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Tanaman {

  int? id;
  String? nama;
  String? namaIlmiah;
  String? kategori;
  String? deskripsi;
  String? iklim;
  String? imageUrl;

  Tanaman({
    this.id,
    this.nama,
    this.namaIlmiah,
    this.kategori,
    this.deskripsi,
    this.iklim,
    this.imageUrl,
  });
  Tanaman.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    nama = json['nama']?.toString();
    namaIlmiah = json['nama_ilmiah']?.toString();
    kategori = json['kategori']?.toString();
    deskripsi = json['deskripsi']?.toString();
    iklim = json['iklim']?.toString();
    imageUrl = json['imageUrl']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nama'] = nama;
    data['nama_ilmiah'] = namaIlmiah;
    data['kategori'] = kategori;
    data['deskripsi'] = deskripsi;
    data['iklim'] = iklim;
    data['imageUrl'] = imageUrl;
    return data;
  }
}
